name: Ci for phpbb

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: |
        cd phpBB
        composer validate --strict

#     - name: Install dependencies
#       run: |
#         cd phpBB
#         php ../composer.phar install

    - name: Sync code to server
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /home/ubuntu/phpbb
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Executing deploy commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/phpbb
          php ../composer.phar install
          
